include ../common/Makefile.common

INCLUDE += -I ../common/

all: $(OPTDIR) $(DEBUGDIR) $(OPTDIR)/factorChainDualDecomp.o $(OPTDIR)/factorDualOpt.o $(OPTDIR)/factorMPBP.o $(OPTDIR)/factorTRWS.o $(OPTDIR)/separatorChainDualDecomp.o $(OPTDIR)/separatorDualOpt.o $(OPTDIR)/sepTRWS.o $(DEBUGDIR)/factorChainDualDecomp.o $(DEBUGDIR)/factorDualOpt.o $(DEBUGDIR)/factorMPBP.o $(DEBUGDIR)/factorTRWS.o $(DEBUGDIR)/separatorChainDualDecomp.o $(DEBUGDIR)/separatorDualOpt.o $(DEBUGDIR)/sepTRWS.o

include ../common/Makefile.finish

